### PR TITLE
Remove Mixpanel User Tracking

### PR DESCRIPTION
**Pull request by sidneys**
Removed injection & call of any mixpanel-related tracking methods.

### CODE REVIEW

**Comment by danielbuechele** [comment]
I want a way to know roughly how many users are using the app. What privacy concerns do you see with mixpanel? I am open to use other ways of counting active users. I don't see any privacy issues with tracking the number of active users.

**Comment by SidneyS** [comment]
Hi @danielbuechele 

The reasoning for tracking is sound, however, in the current form, its not really viable. The reasons are:

- Legal: User behaviour Tracking requires prior consent or an opt-out option, as it is required by several EU Data Privacy laws
- Transparency: A tracking solution should be available to all developers of the application, as it benefits our understanding of problems and bottlenecks
- Security: The mixpanel third party JS tracker payload is obfuscated and thus, mostly opaque. Due to the hybrid JavaScript-heavy nature of the app, injection of arbitrary third party stuff could present a serious risk for user privacy.
- Marketing: Any name-calling with regards to privacy should be avoided at an early stage - e.g. as "that open source messenger which spies on their users", as this app is really awesome and deserves growth :-)

I thus strongly recommend to disable the current implementation asap.

In a second step, lets integrate something more sophisticated (e.g., tracking dedicated views, JS layer exceptions, etc - using Raygun.io, Countly, Google Analytics...) - with a clear option to disable for the users. What do you think

Merry Christmas!
Sid

**Comment by inket** [comment]
Let's get this fix and merged, please. I don't want any tracking of my messaging activities.

I'll throw in real retina support in a pull request if you do 👍

**Comment by anonrig** [comment]
You shouldn't reinvent the wheel. As far as the open sourced code shows, it's only tracking loaded events. Any statistics solution will provide a third party library code integrated to the app itself. Therefore, without any development on both backend/frontend, it's best to use a solution like MixPanel.

User Tracking Feature as a Legal issue is an important matter to consider. But, because the data gathered in this pull request is anonymous, I believe it's not enforced to have a opt-out ability for this statistic.

**Comment by inket** [comment]
> As far as the open sourced code shows, it's only tracking loaded events.

But then Mixpanel has [Autotrack](https://mixpanel.com/help/questions/articles/what-is-autotrack-and-how-do-i-get-started-using-it) so every click and pageview can be tracked without any code.

> But, because the data gathered in this pull request is anonymous, I believe it's not enforced to have a opt-out ability for this statistic.

The URLs themselves have user IDs in them. Would you say that's still anonymous?

**Comment by danielbuechele** [comment]
closing this, as mixpanel is removed in v3

**Pull request closed without merging**
