### PR TITLE
Display user picture in new message notification

### LINKED ISSUE #73: Contact picture in notifications
Would it be possible for notifications to show the contact picture? I know notifications are somewhat tricky, and that probably only Messages.app can do it but hey...

### PR DESCRIPTION
**Pull request by skycocker**
resolves #73

### CODE REVIEW

**Comment by danielbuechele** [comment]
Sorry, hadn't had the time to test this yet. What happens for group conversations?

**Comment by yaycmyk** [comment]
Group convos have a custom avatar right? It can either be set as an image or is a composite image of some of the group members.

**Comment by skycocker** [comment]
@danielbuechele @yaycmyk in the system notification, the Goofy app logo is displayed, and in the left sidebar in goofy app you can see a composite of the conversation members' pictures. Let me know if it's ok for you, and if it is then I'll resolve the conflicts.

**Comment by ankushg** [comment]
any reason this hasn't been merged yet? I'd really like this feature

**Comment by danielbuechele** [comment]
No reason. I just hadn't the time to test it (especially for group conversations). If anyone would have the time to test this PR and confirm it's working, I'll be happy to merge it in.

**Pull request merged**
