### PR TITLE
Swift 3 Update

### PR DESCRIPTION
**Pull request by hrubymar10**
I updated whole project to Swift 3 which is required as of Xcode 8.3 (I
guess)

### CODE REVIEW

**Comment by hrubymar10** [comment]
This is Relese build from latest Swift version 68a9c94:
[Goofy.zip](https://github.com/danielbuechele/goofy/files/1763058/Goofy.zip)

Ignore Sparkle error about signing and available update. AFAIK this version worked well.

**Comment by arainot** [comment]
Alright thanks!

**Comment by hrubymar10** [comment]
@arainot You can now also use mine new Swift 4 fork: https://github.com/hrubymar10/goofy_swift

**Comment by arainot** [comment]
@hrubymar10 Ok thanks, but do you have built versions on it? I can't build the app on my machine for some reason

**Pull request merged**
