### PR TITLE
Self notification bug

### LINKED ISSUE #185: Message from myself bug.
Hi, when I'm sending something from my phone, or via web browser  goofy shows this as a new message (bold font etc.).

### PR DESCRIPTION
**Pull request by rgosain**
Fixes #185

### CODE REVIEW

**Comment by danielbuechele** [comment]
Thanks for cleaning up the selectors. However, your bug fix will only work for English language users. I am wondering if we could find any other solution for this?

**Comment by rgosain** [comment]
Hm, good point. I changed my Facebook language to Spanish and Italian to test it but messenger kept showing me the "You: " text - what languages is it different in?

Something I noticed while looking through the CSS, though is that "You :" is in a different span - it's probably possible to look for `<span>You: </span>`, or ideally `<span>LANGUAGE_SPECIFIC_YOU: </span>` instead - that way if a person just happened to send a message that started with "You: " they wouldn't be interrupted. I can do the latter immediately and then work on a language-agnostic solution.

**Comment by danielbuechele** [comment]
I'm haven't checked it, but I think all languages not using latin letters have localized versions. The additional `<span>` is also set in group messages, so we can't check on this. I can't come up with a good solution for this.
We could use a refined version of yours and look for  `<span>You: </span>`. This would fail if your in a group with someone called "You" and for foreign localizations. I am not sure about this.

**Comment by rgosain** [comment]
I've added the refined version looking for `<span>You: </span>`, but I agree it's not an ideal solution. It seems as though the options are:

1. do nothing
2. continue with this as is, unmodified
3. add foreign localizations of the "You: " span and search for those too

Only option 1 prevents issues with people whose name is that string, option 3 seems manageable given the number of languages facebook supports but may be tedious/slow.

**Comment by danielbuechele** [comment]
I think you go with this version for now. Thanks!

**Comment by joallard** [comment]
I've just switched to other languages, tried fr-ca, fr-fr, es-co, es-es; it seems in none of them has the "You" been translated for now. 

Now in the future that could change, but we could access the locale:

```js
document.documentElement.lang
//=> "fr"
Array.filter(document.body.classList, (e)=>{return e.startsWith("Locale")})[0].replace("Locale_", "")
//=> "fr_CA"
```

And have a map ready so that on ready we go
```js
YALL = {"en": "You", "es": "Usted", "fr_FR": "Vous", "fr_CA": "Vous là"}

onDocumentReady(()=>{
  YOU = fancyMethodToDealWithCountryLocalesAndFetchInYall(bodyLocale)
}
```

**Comment by rgosain** [comment]
I found Turkish using "Sen: " so that could be a chance to use your approach - it's definitely cleaner though I'd want some way to specify "You: " as a default rather than recoding it each time. That might be a good chance to use your solution. Something like this:

```javascript
var YOU_KEYWORDS = {"default": "You: ", "tr_TR": "Sen: "};
var LOCALE = getLocale();
var YOU = YOU_KEYWORDS.hasOwnProperty(locale) ? YOU_KEYWORD[locale] : YOU_KEYWORD["default"];
```

Your solution for getting the locale makes sense. I rewrote it in terms of (less nice) ES5 syntax

```javascript
function getLocale() {
    var locale = Array.prototype.filter.call(document.body.classList, function(e) { 
        return e.startsWith("Locale"); 
    })[0]
    return locale.replace("Locale_", "");
}
```

**Comment by rgosain** [comment]
I finally found a language, Turkish, that translates it. Your solution seems right here - does this look good to everyone? 

```javascript
var YOU_KEYWORDS = {"default": "You: ", "tr_TR": "Sen: "};
var LOCALE = Array.prototype.filter.call(document.body.classList, function(e) { 
    return e.startsWith("Locale"); 
})[0].replace("Locale_", "");
var YOU = YOU_KEYWORDS.hasOwnProperty(LOCALE) ? YOU_KEYWORDS[LOCALE] : YOU_KEYWORDS["default"];
```
I rewrote the locale-getter with ES5 syntax since to my knowledge ES6 isn't supported in the WebView - I'd love to be wrong though.

**Comment by danielbuechele** [comment]
Yes, ES6 is not supported, but your solution @rgosain should work! Can you create a PR?

**Comment by joallard** [comment]
Nice.

ES6: Of course. It was just for demonstration and prototyping purposes as I was writing that on the fly.

One comment:
Safe navigation: Provide for the case FB change their API and stop including "Locale_" on `<body>`.

Example:
```js
localeKeyword = Array.blahFilterblah(...)[0]
LOCALE = localeKeyword ? localeKeyword.replace(...) : "default"
```

**Comment by rgosain** [comment]
Awesome. @joallard do you want to make the PR? It is all your idea

**Comment by joallard** [comment]
@rgosain I can edit the file and Git together a PR, but the reason I haven't is that I don't have xcode installed and don't really know how to test my fix in this context. Thanks for offering the credit though ;) If you really feel up to it, you may make a commit with my name and email on it, you have my permission haha.

**Pull request merged**
